name: documentation

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # run this job at 00:00 UTC every Saturday
    - cron: '0 0 * * 6'

jobs:
  linux:
    name: documentation
    if: github.repository == 'skotlowskii/pmdk'
    runs-on: ubuntu-latest
    env:
      WORKDIR: utils/gha-runners
      SCRIPT: utils/check_docs/split_manpage_tests.py

    steps:
        - name: clone PMDK repository
          uses: actions/checkout@v2

        - name: Build
          run: |
            ./$WORKDIR/build-pmdk.sh build_documentation

        - name: Run tests
          run: python3 ${SCRIPT} --with-pmem2 -r $(pwd) -i $(pwd)/../install
