name: Valgind tests

on:
  pull_request:
  schedule:
    - cron:  '0 18 * * 5'    # At 18:00 on Friday.

jobs:
  linux:
    name: valgrind
    if: github.repository == 'skotlowskii/pmdk'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, rhel],[self-hosted, opensuse]]
    env:
      WORKDIR: utils/gha-runners

    steps:

        - name: Clone the git repo
          uses: actions/checkout@v2

        - name: Get system information
          run: |
            ./$WORKDIR/get-system-info.sh

        - name: Build
          run: |
            ./$WORKDIR/build-pmdk.sh

        - name: Create testconfig file
          run: |
            ./$WORKDIR/create-testconfig.sh

        - name: Run tests - Bash framework - Memcheck
          run: |
            cd src/test/ && ./RUNTESTS -m "force-enable"

        - name: Run tests - Bash framework - Pmemcheck
          run: |
            cd src/test/ && ./RUNTESTS -p "force-enable"

        - name: Run tests - Bash framework - DRD
          run: |
            cd src/test/ && ./RUNTESTS -d "force-enable"

        - name: Run tests - Bash framework - Helgrind
          run: |
            cd src/test/ && ./RUNTESTS -e "force-enable"

        - name: Run tests - Python framework - Memcheck
          run: |
            cd src/test/ && ./RUNTESTS.py -t "check" --force-enable "memcheck"
        
        - name: Run tests - Python framework - Pmemcheck
          run: |
            cd src/test/ && ./RUNTESTS.py -t "check" --force-enable "pmemcheck"

        - name: Run tests - Python framework - DRD
          run: |
            cd src/test/ && ./RUNTESTS.py -t "check" --force-enable "drd"

        - name: Run tests - Python framework - Helgrind
          run: |
            cd src/test/ && ./RUNTESTS.py -t "check" --force-enable "helgrind"
