name: Valgind tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 18 * * 5'    # At 18:00 on Friday.

jobs:
  linux:
    name: valgrind
    if: github.repository == 'skotlowskii/pmdk'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 960
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, rhel],[self-hosted, opensuse]]
        config: [['-m "force-enable"',
                 '-p "force-enable"',
                 '-d "force-enable"',
                 '-e "force-enable"'],
                 ['-t "check" --force-enable memcheck',
                 '-t "check" --force-enable pmemcheck',
                 '-t "check" --force-enable drd',
                 '-t "check" --force-enable helgrind']]
    env:
      WORKDIR: utils/gha-runners

    steps:

        - name: Clone the git repo
          uses: actions/checkout@v2

        - name: Get system information
          run: |
            ./$WORKDIR/get-system-info.sh

        - name: Build
          run: |
            ./$WORKDIR/build-pmdk.sh

        - name: Create testconfig file
          run: |
            ./$WORKDIR/create-testconfig.sh

        - name: Run tests - Bash framework
          run: |
            cd src/test/ && ./RUNTESTS ${{ matrix.config }}

        - name: Run tests - Python framework
          run: |
            cd src/test/ && ./RUNTESTS.py ${{ matrix.config }}
